/**
 * Script to generate the complete Basic English 850 words data file.
 * Reads existing 100 operation words, appends 600 thing words and 150 quality words.
 */
const fs = require('fs');

const targetPath = 'D:/D_CC_vscode/basic-english/js/data/basic_words.js';

// =============================
// 200 PICURABLE THING WORDS
// =============================
const picturableThings = [
  ["angle", "角; 角度", "/ˈæŋɡəl/"],
  ["ant", "蚂蚁", "/ænt/"],
  ["apple", "苹果", "/ˈæpəl/"],
  ["arch", "拱门; 拱形", "/ɑːrtʃ/"],
  ["arm", "手臂; 胳膊", "/ɑːrm/"],
  ["army", "军队; 陆军", "/ˈɑːrmi/"],
  ["baby", "婴儿; 宝宝", "/ˈbeɪbi/"],
  ["bag", "袋子; 包", "/bæɡ/"],
  ["ball", "球; 舞会", "/bɔːl/"],
  ["band", "带子; 乐队", "/bænd/"],
  ["basin", "盆; 水盆", "/ˈbeɪsən/"],
  ["basket", "篮子; 筐", "/ˈbæskɪt/"],
  ["bath", "浴缸; 洗澡", "/bæθ/"],
  ["bed", "床", "/bed/"],
  ["bee", "蜜蜂", "/biː/"],
  ["bell", "铃; 钟", "/bel/"],
  ["berry", "浆果", "/ˈberi/"],
  ["bird", "鸟", "/bɜːrd/"],
  ["blade", "刀片; 刀刃", "/bleɪd/"],
  ["board", "板; 木板", "/bɔːrd/"],
  ["boat", "船; 小船", "/boʊt/"],
  ["bone", "骨头", "/boʊn/"],
  ["book", "书; 书籍", "/bʊk/"],
  ["boot", "靴子", "/buːt/"],
  ["bottle", "瓶子", "/ˈbɒtəl/"],
  ["box", "盒子; 箱子", "/bɒks/"],
  ["boy", "男孩", "/bɔɪ/"],
  ["brain", "大脑; 脑", "/breɪn/"],
  ["brake", "刹车; 制动器", "/breɪk/"],
  ["branch", "树枝; 分支", "/bræntʃ/"],
  ["brick", "砖; 砖块", "/brɪk/"],
  ["bridge", "桥; 桥梁", "/brɪdʒ/"],
  ["brush", "刷子; 画笔", "/brʌʃ/"],
  ["bucket", "桶; 水桶", "/ˈbʌkɪt/"],
  ["bulb", "灯泡; 球茎", "/bʌlb/"],
  ["button", "按钮; 纽扣", "/ˈbʌtən/"],
  ["cake", "蛋糕", "/keɪk/"],
  ["camera", "相机; 照相机", "/ˈkæmərə/"],
  ["card", "卡片; 纸牌", "/kɑːrd/"],
  ["cart", "手推车; 马车", "/kɑːrt/"],
  ["carriage", "马车; 车厢", "/ˈkærɪdʒ/"],
  ["cat", "猫", "/kæt/"],
  ["chain", "链子; 链条", "/tʃeɪn/"],
  ["cheese", "奶酪; 芝士", "/tʃiːz/"],
  ["chest", "胸膛; 箱子", "/tʃest/"],
  ["chin", "下巴", "/tʃɪn/"],
  ["church", "教堂", "/tʃɜːrtʃ/"],
  ["circle", "圆; 圆圈", "/ˈsɜːrkəl/"],
  ["clock", "时钟", "/klɒk/"],
  ["cloud", "云; 云彩", "/klaʊd/"],
  ["coat", "外套; 大衣", "/koʊt/"],
  ["collar", "衣领; 领子", "/ˈkɒlər/"],
  ["comb", "梳子", "/koʊm/"],
  ["cord", "绳子; 线", "/kɔːrd/"],
  ["cow", "奶牛; 母牛", "/kaʊ/"],
  ["cup", "杯子", "/kʌp/"],
  ["curtain", "窗帘; 幕布", "/ˈkɜːrtən/"],
  ["cushion", "垫子; 靠垫", "/ˈkʊʃən/"],
  ["dog", "狗", "/dɒɡ/"],
  ["door", "门", "/dɔːr/"],
  ["drain", "排水管; 下水道", "/dreɪn/"],
  ["drawer", "抽屉", "/drɔːr/"],
  ["dress", "连衣裙; 衣服", "/dres/"],
  ["drop", "滴; 水滴", "/drɒp/"],
  ["ear", "耳朵", "/ɪr/"],
  ["egg", "蛋; 鸡蛋", "/eɡ/"],
  ["engine", "引擎; 发动机", "/ˈendʒɪn/"],
  ["eye", "眼睛", "/aɪ/"],
  ["face", "脸; 面孔", "/feɪs/"],
  ["farm", "农场", "/fɑːrm/"],
  ["feather", "羽毛", "/ˈfeðər/"],
  ["finger", "手指", "/ˈfɪŋɡər/"],
  ["fish", "鱼", "/fɪʃ/"],
  ["flag", "旗子; 旗帜", "/flæɡ/"],
  ["floor", "地板; 楼层", "/flɔːr/"],
  ["fly", "苍蝇", "/flaɪ/"],
  ["foot", "脚; 英尺", "/fʊt/"],
  ["fork", "叉子; 岔口", "/fɔːrk/"],
  ["fowl", "家禽; 禽鸟", "/faʊl/"],
  ["frame", "框架; 画框", "/freɪm/"],
  ["garden", "花园; 菜园", "/ˈɡɑːrdən/"],
  ["girl", "女孩", "/ɡɜːrl/"],
  ["glove", "手套", "/ɡlʌv/"],
  ["goat", "山羊", "/ɡoʊt/"],
  ["gun", "枪", "/ɡʌn/"],
  ["hair", "头发; 毛发", "/her/"],
  ["hammer", "锤子", "/ˈhæmər/"],
  ["hand", "手", "/hænd/"],
  ["hat", "帽子", "/hæt/"],
  ["head", "头; 头部", "/hed/"],
  ["heart", "心脏; 心", "/hɑːrt/"],
  ["hook", "钩子; 挂钩", "/hʊk/"],
  ["horn", "角; 喇叭", "/hɔːrn/"],
  ["horse", "马", "/hɔːrs/"],
  ["hospital", "医院", "/ˈhɒspɪtəl/"],
  ["house", "房子; 房屋", "/haʊs/"],
  ["island", "岛屿", "/ˈaɪlənd/"],
  ["jewel", "宝石; 珠宝", "/ˈdʒuːəl/"],
  ["kettle", "水壶; 水壶", "/ˈketəl/"],
  ["key", "钥匙; 关键", "/kiː/"],
  ["knee", "膝盖", "/niː/"],
  ["knife", "刀; 小刀", "/naɪf/"],
  ["knot", "结; 绳结", "/nɒt/"],
  ["leaf", "叶子; 树叶", "/liːf/"],
  ["leg", "腿", "/leɡ/"],
  ["library", "图书馆", "/ˈlaɪbreri/"],
  ["line", "线; 线条; 行", "/laɪn/"],
  ["lip", "嘴唇", "/lɪp/"],
  ["lock", "锁", "/lɒk/"],
  ["map", "地图", "/mæp/"],
  ["match", "火柴; 比赛", "/mætʃ/"],
  ["monkey", "猴子", "/ˈmʌŋki/"],
  ["moon", "月亮", "/muːn/"],
  ["mouth", "嘴; 嘴巴", "/maʊθ/"],
  ["muscle", "肌肉", "/ˈmʌsəl/"],
  ["nail", "钉子; 指甲", "/neɪl/"],
  ["neck", "脖子; 颈部", "/nek/"],
  ["needle", "针; 缝衣针", "/ˈniːdəl/"],
  ["nerve", "神经", "/nɜːrv/"],
  ["net", "网; 网络", "/net/"],
  ["nose", "鼻子", "/noʊz/"],
  ["nut", "坚果; 螺母", "/nʌt/"],
  ["office", "办公室", "/ˈɒfɪs/"],
  ["orange", "橙子; 橘子", "/ˈɒrɪndʒ/"],
  ["oven", "烤箱; 炉子", "/ˈʌvən/"],
  ["parcel", "包裹", "/ˈpɑːrsəl/"],
  ["pen", "钢笔; 笔", "/pen/"],
  ["pencil", "铅笔", "/ˈpensəl/"],
  ["picture", "图片; 照片", "/ˈpɪktʃər/"],
  ["pig", "猪", "/pɪɡ/"],
  ["pin", "大头针; 别针", "/pɪn/"],
  ["pipe", "管子; 管道", "/paɪp/"],
  ["plane", "飞机", "/pleɪn/"],
  ["plate", "盘子; 碟子", "/pleɪt/"],
  ["plough", "犁", "/plaʊ/"],
  ["pocket", "口袋", "/ˈpɒkɪt/"],
  ["pot", "锅; 罐子", "/pɒt/"],
  ["potato", "土豆; 马铃薯", "/pəˈteɪtoʊ/"],
  ["prison", "监狱", "/ˈprɪzən/"],
  ["pump", "泵; 抽水机", "/pʌmp/"],
  ["rail", "铁轨; 栏杆", "/reɪl/"],
  ["rat", "老鼠; 大鼠", "/ræt/"],
  ["receipt", "收据; 发票", "/rɪˈsiːt/"],
  ["ring", "戒指; 环", "/rɪŋ/"],
  ["rod", "杆; 棒", "/rɒd/"],
  ["roof", "屋顶", "/ruːf/"],
  ["root", "根; 根源", "/ruːt/"],
  ["sail", "帆; 航行", "/seɪl/"],
  ["school", "学校", "/skuːl/"],
  ["scissors", "剪刀", "/ˈsɪzərz/"],
  ["screw", "螺丝; 螺丝钉", "/skruː/"],
  ["seed", "种子", "/siːd/"],
  ["sheep", "羊; 绵羊", "/ʃiːp/"],
  ["shelf", "架子; 搁板", "/ʃelf/"],
  ["ship", "船; 轮船", "/ʃɪp/"],
  ["shirt", "衬衫", "/ʃɜːrt/"],
  ["shoe", "鞋; 鞋子", "/ʃuː/"],
  ["skin", "皮肤", "/skɪn/"],
  ["skirt", "裙子", "/skɜːrt/"],
  ["snake", "蛇", "/sneɪk/"],
  ["sock", "袜子", "/sɒk/"],
  ["spade", "铲子; 铁锹", "/speɪd/"],
  ["sponge", "海绵", "/spʌndʒ/"],
  ["spoon", "勺子; 汤匙", "/spuːn/"],
  ["spring", "弹簧; 春天; 泉水", "/sprɪŋ/"],
  ["square", "正方形; 广场", "/skwer/"],
  ["stamp", "邮票; 印章", "/stæmp/"],
  ["star", "星星; 明星", "/stɑːr/"],
  ["station", "车站; 站", "/ˈsteɪʃən/"],
  ["stem", "茎; 干", "/stem/"],
  ["stick", "棍子; 手杖", "/stɪk/"],
  ["stocking", "长袜", "/ˈstɒkɪŋ/"],
  ["stomach", "胃; 肚子", "/ˈstʌmək/"],
  ["store", "商店; 店铺", "/stɔːr/"],
  ["street", "街道", "/striːt/"],
  ["sun", "太阳", "/sʌn/"],
  ["table", "桌子; 表格", "/ˈteɪbəl/"],
  ["tail", "尾巴", "/teɪl/"],
  ["thread", "线; 线索", "/θred/"],
  ["throat", "喉咙; 咽喉", "/θroʊt/"],
  ["thumb", "拇指", "/θʌm/"],
  ["ticket", "票; 入场券", "/ˈtɪkɪt/"],
  ["toe", "脚趾", "/toʊ/"],
  ["tongue", "舌头; 语言", "/tʌŋ/"],
  ["tooth", "牙齿", "/tuːθ/"],
  ["town", "城镇; 小镇", "/taʊn/"],
  ["train", "火车", "/treɪn/"],
  ["tray", "托盘; 盘子", "/treɪ/"],
  ["tree", "树; 树木", "/triː/"],
  ["trousers", "裤子", "/ˈtraʊzərz/"],
  ["umbrella", "雨伞", "/ʌmˈbrelə/"],
  ["wall", "墙; 墙壁", "/wɔːl/"],
  ["watch", "手表; 观看", "/wɒtʃ/"],
  ["wheel", "轮子; 车轮", "/wiːl/"],
  ["whip", "鞭子", "/wɪp/"],
  ["whistle", "哨子; 口哨", "/ˈwɪsəl/"],
  ["window", "窗户; 窗口", "/ˈwɪndoʊ/"],
  ["wing", "翅膀; 机翼", "/wɪŋ/"],
  ["wire", "电线; 金属丝", "/waɪr/"],
  ["worm", "蠕虫; 虫子", "/wɜːrm/"],
];

// =============================
// 400 GENERAL THING WORDS
// =============================
const generalThings = [
  ["account", "账户; 账目; 叙述", "/əˈkaʊnt/"],
  ["act", "行为; 法案; 表演", "/ækt/"],
  ["addition", "添加; 加法", "/əˈdɪʃən/"],
  ["adjustment", "调整; 调节", "/əˈdʒʌstmənt/"],
  ["advertisement", "广告", "/ˌædvərˈtaɪzmənt/"],
  ["agreement", "协议; 同意", "/əˈɡriːmənt/"],
  ["air", "空气; 空中", "/er/"],
  ["amount", "数量; 金额", "/əˈmaʊnt/"],
  ["amusement", "娱乐; 消遣", "/əˈmjuːzmənt/"],
  ["animal", "动物", "/ˈænɪməl/"],
  ["answer", "答案; 回答", "/ˈænsər/"],
  ["apparatus", "仪器; 设备", "/ˌæpəˈreɪtəs/"],
  ["approval", "批准; 赞成", "/əˈpruːvəl/"],
  ["argument", "争论; 论点", "/ˈɑːrɡjumənt/"],
  ["art", "艺术; 美术", "/ɑːrt/"],
  ["attack", "攻击; 袭击", "/əˈtæk/"],
  ["attempt", "尝试; 企图", "/əˈtempt/"],
  ["attention", "注意力; 关注", "/əˈtenʃən/"],
  ["attraction", "吸引力; 景点", "/əˈtrækʃən/"],
  ["authority", "权威; 当局", "/əˈθɒrəti/"],
  ["back", "背部; 后面", "/bæk/"],
  ["balance", "平衡; 余额", "/ˈbæləns/"],
  ["base", "基础; 底座; 基地", "/beɪs/"],
  ["behavior", "行为; 举止", "/bɪˈheɪvjər/"],
  ["belief", "信念; 信仰", "/bɪˈliːf/"],
  ["birth", "出生; 诞生", "/bɜːrθ/"],
  ["bit", "一点; 少量", "/bɪt/"],
  ["bite", "咬; 一口", "/baɪt/"],
  ["blood", "血液; 血", "/blʌd/"],
  ["blow", "打击; 吹", "/bloʊ/"],
  ["body", "身体; 主体", "/ˈbɒdi/"],
  ["brass", "黄铜; 铜管乐器", "/bræs/"],
  ["bread", "面包", "/bred/"],
  ["breath", "呼吸; 气息", "/breθ/"],
  ["brother", "兄弟; 哥哥; 弟弟", "/ˈbrʌðər/"],
  ["building", "建筑物; 大楼", "/ˈbɪldɪŋ/"],
  ["burn", "烧伤; 灼伤", "/bɜːrn/"],
  ["burst", "爆发; 破裂", "/bɜːrst/"],
  ["business", "商业; 生意; 企业", "/ˈbɪznəs/"],
  ["butter", "黄油; 奶油", "/ˈbʌtər/"],
  ["canvas", "帆布; 画布", "/ˈkænvəs/"],
  ["care", "关心; 照顾", "/ker/"],
  ["cause", "原因; 事业", "/kɔːz/"],
  ["chalk", "粉笔", "/tʃɔːk/"],
  ["chance", "机会; 可能性", "/tʃæns/"],
  ["change", "变化; 改变; 零钱", "/tʃeɪndʒ/"],
  ["cloth", "布; 布料", "/klɒθ/"],
  ["coal", "煤; 煤炭", "/koʊl/"],
  ["color", "颜色", "/ˈkʌlər/"],
  ["comfort", "舒适; 安慰", "/ˈkʌmfərt/"],
  ["committee", "委员会", "/kəˈmɪti/"],
  ["company", "公司; 陪伴", "/ˈkʌmpəni/"],
  ["comparison", "比较; 对比", "/kəmˈpærɪsən/"],
  ["competition", "竞争; 比赛", "/ˌkɒmpəˈtɪʃən/"],
  ["condition", "条件; 状况", "/kənˈdɪʃən/"],
  ["connection", "连接; 关系", "/kəˈnekʃən/"],
  ["control", "控制; 管制", "/kənˈtroʊl/"],
  ["cook", "厨师", "/kʊk/"],
  ["copper", "铜; 红铜", "/ˈkɒpər/"],
  ["copy", "副本; 复制品", "/ˈkɒpi/"],
  ["cork", "软木塞; 软木", "/kɔːrk/"],
  ["cotton", "棉花; 棉布", "/ˈkɒtən/"],
  ["cough", "咳嗽", "/kɒf/"],
  ["country", "国家; 乡村", "/ˈkʌntri/"],
  ["cover", "封面; 覆盖物", "/ˈkʌvər/"],
  ["crack", "裂缝; 裂痕", "/kræk/"],
  ["credit", "信用; 学分; 赊账", "/ˈkredɪt/"],
  ["crime", "犯罪; 罪行", "/kraɪm/"],
  ["crush", "压碎; 挤; 迷恋", "/krʌʃ/"],
  ["cry", "哭泣; 喊叫", "/kraɪ/"],
  ["current", "水流; 电流; 趋势", "/ˈkʌrənt/"],
  ["curve", "曲线; 弯曲", "/kɜːrv/"],
  ["damage", "损害; 损坏", "/ˈdæmɪdʒ/"],
  ["danger", "危险", "/ˈdeɪndʒər/"],
  ["daughter", "女儿", "/ˈdɔːtər/"],
  ["day", "天; 日子; 白天", "/deɪ/"],
  ["death", "死亡", "/deθ/"],
  ["debt", "债务; 欠款", "/det/"],
  ["decision", "决定; 决策", "/dɪˈsɪʒən/"],
  ["degree", "度; 程度; 学位", "/dɪˈɡriː/"],
  ["design", "设计; 图案", "/dɪˈzaɪn/"],
  ["desire", "欲望; 渴望", "/dɪˈzaɪr/"],
  ["destruction", "破坏; 毁灭", "/dɪˈstrʌkʃən/"],
  ["detail", "细节; 详情", "/ˈdiːteɪl/"],
  ["development", "发展; 开发", "/dɪˈveləpmənt/"],
  ["digestion", "消化", "/daɪˈdʒestʃən/"],
  ["direction", "方向; 指导", "/dɪˈrekʃən/"],
  ["discovery", "发现", "/dɪˈskʌvəri/"],
  ["discussion", "讨论; 商议", "/dɪˈskʌʃən/"],
  ["disease", "疾病", "/dɪˈziːz/"],
  ["disgust", "厌恶; 反感", "/dɪsˈɡʌst/"],
  ["distance", "距离; 远方", "/ˈdɪstəns/"],
  ["distribution", "分配; 分布", "/ˌdɪstrɪˈbjuːʃən/"],
  ["division", "分开; 除法; 部门", "/dɪˈvɪʒən/"],
  ["doubt", "怀疑; 疑问", "/daʊt/"],
  ["drink", "饮料; 酒", "/drɪŋk/"],
  ["driving", "驾驶; 驱动", "/ˈdraɪvɪŋ/"],
  ["dust", "灰尘; 尘土", "/dʌst/"],
  ["earth", "地球; 泥土; 大地", "/ɜːrθ/"],
  ["edge", "边缘; 刀刃", "/edʒ/"],
  ["education", "教育", "/ˌedʒuˈkeɪʃən/"],
  ["effect", "效果; 影响", "/ɪˈfekt/"],
  ["end", "结束; 末端", "/end/"],
  ["error", "错误; 误差", "/ˈerər/"],
  ["event", "事件; 活动", "/ɪˈvent/"],
  ["example", "例子; 榜样", "/ɪɡˈzæmpəl/"],
  ["exchange", "交换; 兑换; 交易所", "/ɪksˈtʃeɪndʒ/"],
  ["existence", "存在; 生存", "/ɪɡˈzɪstəns/"],
  ["expansion", "扩张; 扩展", "/ɪkˈspænʃən/"],
  ["experience", "经验; 体验", "/ɪkˈspɪriəns/"],
  ["expert", "专家; 行家", "/ˈekspɜːrt/"],
  ["fact", "事实; 真相", "/fækt/"],
  ["fall", "秋天; 落下", "/fɔːl/"],
  ["family", "家庭; 家人", "/ˈfæməli/"],
  ["father", "父亲; 爸爸", "/ˈfɑːðər/"],
  ["fear", "恐惧; 害怕", "/fɪr/"],
  ["feeling", "感觉; 情感", "/ˈfiːlɪŋ/"],
  ["fiction", "小说; 虚构", "/ˈfɪkʃən/"],
  ["field", "田野; 领域; 场地", "/fiːld/"],
  ["fight", "战斗; 打架", "/faɪt/"],
  ["fire", "火; 火灾", "/faɪr/"],
  ["flame", "火焰; 火苗", "/fleɪm/"],
  ["flight", "飞行; 航班", "/flaɪt/"],
  ["flower", "花; 花朵", "/ˈflaʊər/"],
  ["fold", "折叠; 褶层", "/foʊld/"],
  ["food", "食物; 食品", "/fuːd/"],
  ["force", "力量; 武力; 力", "/fɔːrs/"],
  ["form", "形式; 表格; 形态", "/fɔːrm/"],
  ["friend", "朋友", "/frend/"],
  ["front", "前面; 正面; 前线", "/frʌnt/"],
  ["fruit", "水果; 果实", "/fruːt/"],
  ["glass", "玻璃; 玻璃杯", "/ɡlæs/"],
  ["gold", "金子; 黄金", "/ɡoʊld/"],
  ["government", "政府", "/ˈɡʌvərnmənt/"],
  ["grain", "谷物; 粮食; 颗粒", "/ɡreɪn/"],
  ["grass", "草; 草地", "/ɡræs/"],
  ["grip", "紧握; 抓力", "/ɡrɪp/"],
  ["group", "组; 群; 团体", "/ɡruːp/"],
  ["growth", "生长; 增长", "/ɡroʊθ/"],
  ["guide", "向导; 指南", "/ɡaɪd/"],
  ["harbor", "港口; 海港", "/ˈhɑːrbər/"],
  ["harmony", "和谐; 融洽", "/ˈhɑːrməni/"],
  ["hate", "仇恨; 憎恨", "/heɪt/"],
  ["hearing", "听力; 听觉; 听证会", "/ˈhɪrɪŋ/"],
  ["heat", "热量; 热度; 高温", "/hiːt/"],
  ["help", "帮助; 援助", "/help/"],
  ["history", "历史", "/ˈhɪstəri/"],
  ["hole", "洞; 孔", "/hoʊl/"],
  ["hope", "希望; 期望", "/hoʊp/"],
  ["hour", "小时; 时刻", "/aʊr/"],
  ["humor", "幽默", "/ˈhjuːmər/"],
  ["ice", "冰", "/aɪs/"],
  ["idea", "想法; 主意", "/aɪˈdiːə/"],
  ["impulse", "冲动; 脉冲", "/ˈɪmpʌls/"],
  ["increase", "增加; 增长", "/ˈɪnkriːs/"],
  ["industry", "工业; 产业", "/ˈɪndəstri/"],
  ["ink", "墨水; 油墨", "/ɪŋk/"],
  ["insect", "昆虫", "/ˈɪnsekt/"],
  ["instrument", "仪器; 乐器; 工具", "/ˈɪnstrəmənt/"],
  ["insurance", "保险", "/ɪnˈʃʊrəns/"],
  ["interest", "兴趣; 利息; 利益", "/ˈɪntrəst/"],
  ["invention", "发明", "/ɪnˈvenʃən/"],
  ["iron", "铁; 熨斗", "/ˈaɪərn/"],
  ["jelly", "果冻; 胶状物", "/ˈdʒeli/"],
  ["join", "连接; 加入", "/dʒɔɪn/"],
  ["journey", "旅程; 旅行", "/ˈdʒɜːrni/"],
  ["judge", "法官; 裁判", "/dʒʌdʒ/"],
  ["jump", "跳跃", "/dʒʌmp/"],
  ["kick", "踢", "/kɪk/"],
  ["kiss", "吻; 亲吻", "/kɪs/"],
  ["knowledge", "知识; 学问", "/ˈnɒlɪdʒ/"],
  ["land", "土地; 陆地", "/lænd/"],
  ["language", "语言", "/ˈlæŋɡwɪdʒ/"],
  ["laugh", "笑; 笑声", "/læf/"],
  ["law", "法律; 规律", "/lɔː/"],
  ["lead", "铅; 领导", "/led/"],
  ["learning", "学习; 学问", "/ˈlɜːrnɪŋ/"],
  ["leather", "皮革", "/ˈleðər/"],
  ["letter", "信; 字母", "/ˈletər/"],
  ["level", "水平; 级别", "/ˈlevəl/"],
  ["lift", "电梯; 举起", "/lɪft/"],
  ["light", "光; 光线; 灯", "/laɪt/"],
  ["limit", "限制; 界限", "/ˈlɪmɪt/"],
  ["linen", "亚麻布; 床单", "/ˈlɪnɪn/"],
  ["liquid", "液体", "/ˈlɪkwɪd/"],
  ["list", "列表; 清单", "/lɪst/"],
  ["look", "看; 外表; 目光", "/lʊk/"],
  ["loss", "损失; 丢失", "/lɒs/"],
  ["love", "爱; 爱情", "/lʌv/"],
  ["machine", "机器; 机械", "/məˈʃiːn/"],
  ["man", "男人; 人", "/mæn/"],
  ["manager", "经理; 管理者", "/ˈmænɪdʒər/"],
  ["mark", "标记; 记号; 分数", "/mɑːrk/"],
  ["market", "市场; 集市", "/ˈmɑːrkɪt/"],
  ["mass", "大量; 群众; 质量", "/mæs/"],
  ["meal", "餐; 一顿饭", "/miːl/"],
  ["measure", "测量; 措施; 尺寸", "/ˈmeʒər/"],
  ["meat", "肉; 肉类", "/miːt/"],
  ["meeting", "会议; 会面", "/ˈmiːtɪŋ/"],
  ["memory", "记忆; 回忆", "/ˈmeməri/"],
  ["metal", "金属", "/ˈmetəl/"],
  ["middle", "中间; 中部", "/ˈmɪdəl/"],
  ["milk", "牛奶; 奶", "/mɪlk/"],
  ["mind", "头脑; 心思; 想法", "/maɪnd/"],
  ["mine", "矿; 矿井", "/maɪn/"],
  ["minute", "分钟", "/ˈmɪnɪt/"],
  ["mist", "薄雾; 雾", "/mɪst/"],
  ["money", "钱; 金钱", "/ˈmʌni/"],
  ["month", "月; 月份", "/mʌnθ/"],
  ["morning", "早晨; 上午", "/ˈmɔːrnɪŋ/"],
  ["mother", "母亲; 妈妈", "/ˈmʌðər/"],
  ["motion", "运动; 动作", "/ˈmoʊʃən/"],
  ["mountain", "山; 山脉", "/ˈmaʊntən/"],
  ["move", "移动; 搬家; 步骤", "/muːv/"],
  ["music", "音乐", "/ˈmjuːzɪk/"],
  ["name", "名字; 名称", "/neɪm/"],
  ["nation", "国家; 民族", "/ˈneɪʃən/"],
  ["need", "需要; 需求", "/niːd/"],
  ["news", "新闻; 消息", "/nuːz/"],
  ["night", "夜晚; 晚上", "/naɪt/"],
  ["noise", "噪音; 喧闹声", "/nɔɪz/"],
  ["note", "笔记; 便条; 音符", "/noʊt/"],
  ["number", "数字; 号码; 数量", "/ˈnʌmbər/"],
  ["observation", "观察; 观测", "/ˌɒbzərˈveɪʃən/"],
  ["offer", "提议; 报价; 录取", "/ˈɒfər/"],
  ["oil", "油; 石油", "/ɔɪl/"],
  ["operation", "操作; 手术; 运营", "/ˌɒpəˈreɪʃən/"],
  ["opinion", "意见; 看法", "/əˈpɪnjən/"],
  ["order", "顺序; 命令; 订单", "/ˈɔːrdər/"],
  ["organization", "组织; 机构", "/ˌɔːrɡənaɪˈzeɪʃən/"],
  ["ornament", "装饰品; 点缀", "/ˈɔːrnəmənt/"],
  ["owner", "所有者; 主人", "/ˈoʊnər/"],
  ["page", "页; 页面", "/peɪdʒ/"],
  ["pain", "疼痛; 痛苦", "/peɪn/"],
  ["paint", "油漆; 颜料", "/peɪnt/"],
  ["paper", "纸; 文件; 论文", "/ˈpeɪpər/"],
  ["part", "部分; 零件; 角色", "/pɑːrt/"],
  ["paste", "浆糊; 面团", "/peɪst/"],
  ["payment", "付款; 支付", "/ˈpeɪmənt/"],
  ["peace", "和平; 安宁", "/piːs/"],
  ["person", "人; 个人", "/ˈpɜːrsən/"],
  ["place", "地方; 地点; 位置", "/pleɪs/"],
  ["plant", "植物; 工厂", "/plænt/"],
  ["play", "戏剧; 游戏; 玩耍", "/pleɪ/"],
  ["pleasure", "快乐; 乐趣", "/ˈpleʒər/"],
  ["point", "点; 要点; 分数", "/pɔɪnt/"],
  ["poison", "毒药; 毒物", "/ˈpɔɪzən/"],
  ["polish", "上光剂; 擦亮; 抛光", "/ˈpɒlɪʃ/"],
  ["porter", "搬运工; 门房", "/ˈpɔːrtər/"],
  ["position", "位置; 职位; 立场", "/pəˈzɪʃən/"],
  ["powder", "粉末; 粉", "/ˈpaʊdər/"],
  ["power", "力量; 权力; 电力", "/ˈpaʊər/"],
  ["price", "价格; 代价", "/praɪs/"],
  ["print", "印刷; 印刷品", "/prɪnt/"],
  ["process", "过程; 工序", "/ˈprɒses/"],
  ["produce", "农产品; 产物", "/ˈprɒdjuːs/"],
  ["profit", "利润; 收益", "/ˈprɒfɪt/"],
  ["property", "财产; 性质; 房产", "/ˈprɒpərti/"],
  ["prose", "散文", "/proʊz/"],
  ["protest", "抗议; 反对", "/ˈproʊtest/"],
  ["pull", "拉; 拉力; 引力", "/pʊl/"],
  ["punch", "拳打; 打孔器", "/pʌntʃ/"],
  ["punishment", "惩罚; 处罚", "/ˈpʌnɪʃmənt/"],
  ["purpose", "目的; 意图", "/ˈpɜːrpəs/"],
  ["push", "推; 推动", "/pʊʃ/"],
  ["quality", "质量; 品质", "/ˈkwɒləti/"],
  ["question", "问题; 疑问", "/ˈkwestʃən/"],
  ["rain", "雨; 雨水", "/reɪn/"],
  ["range", "范围; 山脉; 幅度", "/reɪndʒ/"],
  ["rate", "比率; 费率; 速度", "/reɪt/"],
  ["ray", "光线; 射线", "/reɪ/"],
  ["reaction", "反应; 回应", "/riˈækʃən/"],
  ["reading", "阅读; 读物; 读数", "/ˈriːdɪŋ/"],
  ["reason", "原因; 理由; 理性", "/ˈriːzən/"],
  ["record", "记录; 唱片; 纪录", "/ˈrekɔːrd/"],
  ["regret", "遗憾; 后悔", "/rɪˈɡret/"],
  ["relation", "关系; 联系", "/rɪˈleɪʃən/"],
  ["religion", "宗教; 信仰", "/rɪˈlɪdʒən/"],
  ["representative", "代表; 代理人", "/ˌreprɪˈzentətɪv/"],
  ["request", "请求; 要求", "/rɪˈkwest/"],
  ["respect", "尊重; 尊敬", "/rɪˈspekt/"],
  ["rest", "休息; 其余", "/rest/"],
  ["reward", "奖励; 回报", "/rɪˈwɔːrd/"],
  ["rhythm", "节奏; 韵律", "/ˈrɪðəm/"],
  ["rice", "米饭; 稻米", "/raɪs/"],
  ["river", "河流; 江", "/ˈrɪvər/"],
  ["road", "道路; 公路", "/roʊd/"],
  ["roll", "卷; 滚动; 名册", "/roʊl/"],
  ["room", "房间; 空间", "/ruːm/"],
  ["rub", "摩擦", "/rʌb/"],
  ["rule", "规则; 统治", "/ruːl/"],
  ["run", "跑; 运行; 连续", "/rʌn/"],
  ["salt", "盐", "/sɔːlt/"],
  ["sand", "沙子", "/sænd/"],
  ["scale", "规模; 比例; 鳞; 天平", "/skeɪl/"],
  ["science", "科学", "/ˈsaɪəns/"],
  ["sea", "海; 海洋", "/siː/"],
  ["seat", "座位; 席位", "/siːt/"],
  ["secretary", "秘书; 书记", "/ˈsekrəteri/"],
  ["selection", "选择; 挑选", "/sɪˈlekʃən/"],
  ["self", "自己; 自我", "/self/"],
  ["sense", "感觉; 感官; 意义", "/sens/"],
  ["servant", "仆人; 佣人; 公务员", "/ˈsɜːrvənt/"],
  ["sex", "性别; 性", "/seks/"],
  ["shade", "阴凉处; 阴影; 色调", "/ʃeɪd/"],
  ["shake", "摇动; 震动", "/ʃeɪk/"],
  ["shame", "羞耻; 羞愧", "/ʃeɪm/"],
  ["shock", "震惊; 冲击", "/ʃɒk/"],
  ["side", "边; 侧面; 一方", "/saɪd/"],
  ["sign", "标志; 符号; 迹象", "/saɪn/"],
  ["silk", "丝绸", "/sɪlk/"],
  ["silver", "银; 银色", "/ˈsɪlvər/"],
  ["sister", "姐妹; 姐姐; 妹妹", "/ˈsɪstər/"],
  ["size", "大小; 尺寸", "/saɪz/"],
  ["sky", "天空", "/skaɪ/"],
  ["sleep", "睡眠; 睡觉", "/sliːp/"],
  ["slip", "滑动; 滑倒; 纸条", "/slɪp/"],
  ["slope", "斜坡; 坡度", "/sloʊp/"],
  ["smash", "粉碎; 猛击; 撞击", "/smæʃ/"],
  ["smell", "气味; 嗅觉", "/smel/"],
  ["smile", "微笑", "/smaɪl/"],
  ["smoke", "烟; 烟雾", "/smoʊk/"],
  ["sneeze", "喷嚏", "/sniːz/"],
  ["snow", "雪; 雪花", "/snoʊ/"],
  ["soap", "肥皂", "/soʊp/"],
  ["society", "社会; 协会", "/səˈsaɪəti/"],
  ["son", "儿子", "/sʌn/"],
  ["song", "歌曲; 歌", "/sɒŋ/"],
  ["sort", "种类; 类别", "/sɔːrt/"],
  ["sound", "声音", "/saʊnd/"],
  ["soup", "汤", "/suːp/"],
  ["space", "空间; 太空", "/speɪs/"],
  ["stage", "舞台; 阶段", "/steɪdʒ/"],
  ["start", "开始; 起点", "/stɑːrt/"],
  ["statement", "声明; 陈述", "/ˈsteɪtmənt/"],
  ["steam", "蒸汽; 水蒸气", "/stiːm/"],
  ["steel", "钢铁", "/stiːl/"],
  ["step", "步骤; 脚步; 台阶", "/step/"],
  ["stitch", "针脚; 一针", "/stɪtʃ/"],
  ["stone", "石头", "/stoʊn/"],
  ["stop", "停止; 车站", "/stɒp/"],
  ["story", "故事; 小说", "/ˈstɔːri/"],
  ["stretch", "伸展; 伸长", "/stretʃ/"],
  ["structure", "结构; 建筑", "/ˈstrʌktʃər/"],
  ["substance", "物质; 实质", "/ˈsʌbstəns/"],
  ["sugar", "糖; 白糖", "/ˈʃʊɡər/"],
  ["suggestion", "建议; 暗示", "/səˈdʒestʃən/"],
  ["summer", "夏天; 夏季", "/ˈsʌmər/"],
  ["support", "支持; 支撑", "/səˈpɔːrt/"],
  ["surprise", "惊喜; 惊讶", "/sərˈpraɪz/"],
  ["swim", "游泳", "/swɪm/"],
  ["system", "系统; 体系", "/ˈsɪstəm/"],
  ["talk", "谈话; 交谈; 演讲", "/tɔːk/"],
  ["taste", "味道; 品味", "/teɪst/"],
  ["tax", "税; 税款", "/tæks/"],
  ["teaching", "教学; 教导", "/ˈtiːtʃɪŋ/"],
  ["tendency", "趋势; 倾向", "/ˈtendənsi/"],
  ["test", "测试; 考试", "/test/"],
  ["theory", "理论; 学说", "/ˈθɪəri/"],
  ["thing", "东西; 事物; 事情", "/θɪŋ/"],
  ["thought", "思想; 想法", "/θɔːt/"],
  ["thunder", "雷; 雷声", "/ˈθʌndər/"],
  ["time", "时间; 次数", "/taɪm/"],
  ["tin", "锡; 罐头", "/tɪn/"],
  ["top", "顶部; 顶端", "/tɒp/"],
  ["touch", "触觉; 接触", "/tʌtʃ/"],
  ["trade", "贸易; 交易; 行业", "/treɪd/"],
  ["transport", "运输; 交通", "/ˈtrænspɔːrt/"],
  ["trick", "诡计; 把戏; 技巧", "/trɪk/"],
  ["trouble", "麻烦; 困难", "/ˈtrʌbəl/"],
  ["turn", "轮流; 转弯; 转变", "/tɜːrn/"],
  ["twist", "扭曲; 弯曲; 转折", "/twɪst/"],
  ["unit", "单位; 单元", "/ˈjuːnɪt/"],
  ["use", "使用; 用途", "/juːs/"],
  ["value", "价值; 数值", "/ˈvæljuː/"],
  ["verse", "诗; 诗句; 韵文", "/vɜːrs/"],
  ["vessel", "容器; 船只; 血管", "/ˈvesəl/"],
  ["view", "景色; 观点; 视野", "/vjuː/"],
  ["voice", "声音; 嗓音", "/vɔɪs/"],
  ["walk", "步行; 散步", "/wɔːk/"],
  ["war", "战争", "/wɔːr/"],
  ["wash", "洗涤; 清洗", "/wɒʃ/"],
  ["waste", "废物; 浪费", "/weɪst/"],
  ["water", "水", "/ˈwɔːtər/"],
  ["wave", "波浪; 波动", "/weɪv/"],
  ["wax", "蜡; 蜂蜡", "/wæks/"],
  ["way", "方式; 方法; 路", "/weɪ/"],
  ["weather", "天气; 气候", "/ˈweðər/"],
  ["week", "周; 星期", "/wiːk/"],
  ["weight", "重量; 体重", "/weɪt/"],
  ["wind", "风", "/wɪnd/"],
  ["wine", "葡萄酒; 酒", "/waɪn/"],
  ["winter", "冬天; 冬季", "/ˈwɪntər/"],
  ["woman", "女人; 女性", "/ˈwʊmən/"],
  ["wood", "木头; 木材", "/wʊd/"],
  ["wool", "羊毛; 毛线", "/wʊl/"],
  ["word", "词; 单词; 话语", "/wɜːrd/"],
  ["work", "工作; 作品", "/wɜːrk/"],
  ["wound", "伤口; 创伤", "/wuːnd/"],
  ["writing", "写作; 文字; 书法", "/ˈraɪtɪŋ/"],
];

// =============================
// 100 GENERAL QUALITY WORDS
// =============================
const generalQualities = [
  ["able", "有能力的; 能够的", "/ˈeɪbəl/"],
  ["acid", "酸的; 酸性的", "/ˈæsɪd/"],
  ["angry", "生气的; 愤怒的", "/ˈæŋɡri/"],
  ["automatic", "自动的", "/ˌɔːtəˈmætɪk/"],
  ["beautiful", "美丽的; 漂亮的", "/ˈbjuːtɪfəl/"],
  ["black", "黑色的", "/blæk/"],
  ["boiling", "沸腾的; 极热的", "/ˈbɔɪlɪŋ/"],
  ["bright", "明亮的; 聪明的", "/braɪt/"],
  ["broken", "破碎的; 损坏的", "/ˈbroʊkən/"],
  ["brown", "棕色的; 褐色的", "/braʊn/"],
  ["cheap", "便宜的; 廉价的", "/tʃiːp/"],
  ["chemical", "化学的", "/ˈkemɪkəl/"],
  ["chief", "主要的; 首要的", "/tʃiːf/"],
  ["clean", "干净的; 清洁的", "/kliːn/"],
  ["clear", "清楚的; 清晰的; 晴朗的", "/klɪr/"],
  ["common", "常见的; 普通的; 共同的", "/ˈkɒmən/"],
  ["complex", "复杂的", "/ˈkɒmpleks/"],
  ["conscious", "有意识的; 清醒的", "/ˈkɒnʃəs/"],
  ["cut", "切开的; 剪下的", "/kʌt/"],
  ["deep", "深的; 深奥的", "/diːp/"],
  ["dependent", "依赖的; 依靠的", "/dɪˈpendənt/"],
  ["early", "早的; 早期的; 提早的", "/ˈɜːrli/"],
  ["elastic", "有弹性的; 灵活的", "/ɪˈlæstɪk/"],
  ["electric", "电的; 电动的", "/ɪˈlektrɪk/"],
  ["equal", "相等的; 平等的", "/ˈiːkwəl/"],
  ["fat", "胖的; 肥的", "/fæt/"],
  ["fertile", "肥沃的; 多产的", "/ˈfɜːrtaɪl/"],
  ["first", "第一的; 首先的", "/fɜːrst/"],
  ["fixed", "固定的; 不变的", "/fɪkst/"],
  ["flat", "平的; 平坦的", "/flæt/"],
  ["free", "自由的; 免费的", "/friː/"],
  ["frequent", "频繁的; 经常的", "/ˈfriːkwənt/"],
  ["full", "满的; 完整的; 饱的", "/fʊl/"],
  ["general", "一般的; 普遍的; 总的", "/ˈdʒenərəl/"],
  ["good", "好的; 优良的", "/ɡʊd/"],
  ["great", "伟大的; 极大的; 好的", "/ɡreɪt/"],
  ["grey", "灰色的", "/ɡreɪ/"],
  ["hanging", "悬挂的; 垂下的", "/ˈhæŋɪŋ/"],
  ["happy", "快乐的; 幸福的", "/ˈhæpi/"],
  ["hard", "硬的; 困难的; 努力的", "/hɑːrd/"],
  ["healthy", "健康的", "/ˈhelθi/"],
  ["high", "高的; 高级的", "/haɪ/"],
  ["hollow", "空心的; 虚伪的", "/ˈhɒloʊ/"],
  ["important", "重要的; 重大的", "/ɪmˈpɔːrtənt/"],
  ["kind", "友善的; 亲切的", "/kaɪnd/"],
  ["like", "相似的; 同样的", "/laɪk/"],
  ["living", "活着的; 有生命的", "/ˈlɪvɪŋ/"],
  ["long", "长的; 长久的", "/lɒŋ/"],
  ["married", "已婚的", "/ˈmærid/"],
  ["material", "物质的; 重要的", "/məˈtɪriəl/"],
  ["medical", "医学的; 医疗的", "/ˈmedɪkəl/"],
  ["military", "军事的; 军队的", "/ˈmɪlɪteri/"],
  ["natural", "自然的; 天生的", "/ˈnætʃərəl/"],
  ["necessary", "必要的; 必需的", "/ˈnesəseri/"],
  ["new", "新的; 新鲜的", "/njuː/"],
  ["normal", "正常的; 标准的", "/ˈnɔːrməl/"],
  ["open", "开着的; 开放的; 敞开的", "/ˈoʊpən/"],
  ["parallel", "平行的; 并行的", "/ˈpærəlel/"],
  ["past", "过去的; 以往的", "/pæst/"],
  ["physical", "物理的; 身体的; 物质的", "/ˈfɪzɪkəl/"],
  ["political", "政治的", "/pəˈlɪtɪkəl/"],
  ["poor", "贫穷的; 可怜的; 差的", "/pʊr/"],
  ["possible", "可能的", "/ˈpɒsəbəl/"],
  ["present", "现在的; 在场的; 出席的", "/ˈprezənt/"],
  ["private", "私人的; 私密的", "/ˈpraɪvɪt/"],
  ["probable", "很可能的; 大概的", "/ˈprɒbəbəl/"],
  ["public", "公共的; 公开的; 公众的", "/ˈpʌblɪk/"],
  ["quick", "快的; 迅速的", "/kwɪk/"],
  ["quiet", "安静的; 平静的", "/ˈkwaɪət/"],
  ["ready", "准备好的; 乐意的", "/ˈredi/"],
  ["red", "红色的", "/red/"],
  ["regular", "规律的; 定期的; 常规的", "/ˈreɡjələr/"],
  ["responsible", "负责的; 有责任的", "/rɪˈspɒnsəbəl/"],
  ["right", "正确的; 右边的; 合适的", "/raɪt/"],
  ["round", "圆的; 圆形的", "/raʊnd/"],
  ["same", "相同的; 同样的", "/seɪm/"],
  ["second", "第二的; 次等的", "/ˈsekənd/"],
  ["separate", "分开的; 单独的", "/ˈsepərət/"],
  ["serious", "严肃的; 严重的; 认真的", "/ˈsɪriəs/"],
  ["sharp", "锋利的; 敏锐的; 尖锐的", "/ʃɑːrp/"],
  ["smooth", "光滑的; 顺畅的; 平稳的", "/smuːð/"],
  ["sticky", "黏的; 黏性的", "/ˈstɪki/"],
  ["stiff", "僵硬的; 硬的; 拘谨的", "/stɪf/"],
  ["straight", "直的; 直接的; 坦率的", "/streɪt/"],
  ["strong", "强壮的; 强大的; 坚固的", "/strɒŋ/"],
  ["sudden", "突然的; 意外的", "/ˈsʌdən/"],
  ["sweet", "甜的; 甜的; 可爱的", "/swiːt/"],
  ["tall", "高的; 高大的", "/tɔːl/"],
  ["thick", "厚的; 粗的; 浓的", "/θɪk/"],
  ["tight", "紧的; 牢固的; 紧密的", "/taɪt/"],
  ["tired", "疲劳的; 累的; 厌倦的", "/taɪrd/"],
  ["true", "真实的; 真正的; 正确的", "/truː/"],
  ["violent", "暴力的; 猛烈的", "/ˈvaɪələnt/"],
  ["waiting", "等待的; 等候的", "/ˈweɪtɪŋ/"],
  ["warm", "温暖的; 热情的", "/wɔːrm/"],
  ["wet", "湿的; 潮湿的", "/wet/"],
  ["wide", "宽的; 宽阔的; 广泛的", "/waɪd/"],
  ["wise", "明智的; 聪明的", "/waɪz/"],
  ["yellow", "黄色的", "/ˈjeloʊ/"],
  ["young", "年轻的; 幼小的", "/jʌŋ/"],
];

// =============================
// 50 OPPOSITE QUALITY WORDS
// =============================
const oppositeQualities = [
  ["awake", "醒着的; 清醒的", "/əˈweɪk/"],
  ["bad", "坏的; 不好的; 差的", "/bæd/"],
  ["bent", "弯曲的; 弯的", "/bent/"],
  ["bitter", "苦的; 痛苦的", "/ˈbɪtər/"],
  ["blue", "蓝色的; 忧郁的", "/bluː/"],
  ["certain", "确定的; 肯定的; 某个", "/ˈsɜːrtən/"],
  ["cold", "冷的; 寒冷的; 冷淡的", "/koʊld/"],
  ["complete", "完整的; 完全的; 完成的", "/kəmˈpliːt/"],
  ["cruel", "残忍的; 残酷的", "/ˈkruːəl/"],
  ["dark", "黑暗的; 暗的; 深色的", "/dɑːrk/"],
  ["dead", "死的; 无生命的", "/ded/"],
  ["dear", "亲爱的; 珍贵的; 昂贵的", "/dɪr/"],
  ["delicate", "精致的; 脆弱的; 微妙的", "/ˈdelɪkət/"],
  ["different", "不同的; 有差别的", "/ˈdɪfərənt/"],
  ["dirty", "脏的; 肮脏的", "/ˈdɜːrti/"],
  ["dry", "干的; 干燥的", "/draɪ/"],
  ["false", "假的; 错误的; 虚假的", "/fɔːls/"],
  ["feeble", "虚弱的; 无力的", "/ˈfiːbəl/"],
  ["female", "女性的; 雌性的", "/ˈfiːmeɪl/"],
  ["foolish", "愚蠢的; 傻的", "/ˈfuːlɪʃ/"],
  ["future", "未来的; 将来的", "/ˈfjuːtʃər/"],
  ["green", "绿色的", "/ɡriːn/"],
  ["ill", "生病的; 坏的; 有害的", "/ɪl/"],
  ["last", "最后的; 上一个的", "/læst/"],
  ["late", "晚的; 迟的; 已故的", "/leɪt/"],
  ["left", "左边的; 剩下的", "/left/"],
  ["loose", "松的; 宽松的; 自由的", "/luːs/"],
  ["loud", "大声的; 响亮的", "/laʊd/"],
  ["low", "低的; 矮的; 浅的", "/loʊ/"],
  ["mixed", "混合的; 混杂的", "/mɪkst/"],
  ["narrow", "窄的; 狭窄的; 狭隘的", "/ˈnæroʊ/"],
  ["old", "老的; 旧的; 年长的", "/oʊld/"],
  ["opposite", "相反的; 对面的", "/ˈɒpəzɪt/"],
  ["public", "公共的; 公开的; 公众的", "/ˈpʌblɪk/"],
  ["rough", "粗糙的; 粗暴的; 大致的", "/rʌf/"],
  ["sad", "悲伤的; 难过的", "/sæd/"],
  ["safe", "安全的; 平安的", "/seɪf/"],
  ["secret", "秘密的; 机密的", "/ˈsiːkrɪt/"],
  ["short", "短的; 矮的; 不足的", "/ʃɔːrt/"],
  ["shut", "关闭的; 关上的", "/ʃʌt/"],
  ["simple", "简单的; 朴素的", "/ˈsɪmpəl/"],
  ["slow", "慢的; 缓慢的", "/sloʊ/"],
  ["small", "小的; 少的", "/smɔːl/"],
  ["soft", "软的; 柔软的; 温和的", "/sɒft/"],
  ["solid", "固体的; 坚固的; 实心的", "/ˈsɒlɪd/"],
  ["special", "特别的; 特殊的", "/ˈspeʃəl/"],
  ["strange", "奇怪的; 陌生的", "/streɪndʒ/"],
  ["thin", "薄的; 瘦的; 稀的", "/θɪn/"],
  ["white", "白色的", "/waɪt/"],
  ["wrong", "错误的; 不对的", "/rɒŋ/"],
];

// =============================
// BUILD FUNCTIONS
// =============================
function buildThingWords(picturableList, generalList) {
  const words = [];
  let id = 1;

  // 200 picturable things (th_001 to th_200)
  for (const [word, chinese, phonetic] of picturableList) {
    words.push({
      id: `th_${String(id).padStart(3, '0')}`,
      word,
      chinese,
      type: 'thing',
      phonetic,
      combinations: [],
      paraphrasing_examples: [],
    });
    id++;
  }

  // 400 general things (th_201 to th_600)
  for (const [word, chinese, phonetic] of generalList) {
    words.push({
      id: `th_${String(id).padStart(3, '0')}`,
      word,
      chinese,
      type: 'thing',
      phonetic,
      combinations: [],
      paraphrasing_examples: [],
    });
    id++;
  }

  return words;
}

function buildQualityWords(generalList, oppositeList) {
  const words = [];
  let id = 1;

  // 100 general qualities (qa_001 to qa_100)
  for (const [word, chinese, phonetic] of generalList) {
    words.push({
      id: `qa_${String(id).padStart(3, '0')}`,
      word,
      chinese,
      type: 'quality',
      phonetic,
      combinations: [],
      paraphrasing_examples: [],
    });
    id++;
  }

  // 50 opposite qualities (qa_101 to qa_150)
  for (const [word, chinese, phonetic] of oppositeList) {
    words.push({
      id: `qa_${String(id).padStart(3, '0')}`,
      word,
      chinese,
      type: 'quality',
      phonetic,
      combinations: [],
      paraphrasing_examples: [],
    });
    id++;
  }

  return words;
}

// =============================
// MAIN
// =============================

// 1. Read existing file and extract operation words
const rawContent = fs.readFileSync(targetPath, 'utf-8');

// Extract JSON array from `window.BASIC_WORDS = [...];`
const arrayMatch = rawContent.match(/window\.BASIC_WORDS\s*=\s*(\[[\s\S]*\]);/);
if (!arrayMatch) {
  console.error('ERROR: Could not parse existing file. Expected window.BASIC_WORDS = [...];');
  process.exit(1);
}

let operationWords;
try {
  operationWords = JSON.parse(arrayMatch[1]);
} catch (e) {
  console.error('ERROR: Failed to parse JSON from existing file:', e.message);
  process.exit(1);
}

console.log(`Loaded ${operationWords.length} operation words from existing file.`);

// 2. Generate thing words and quality words
const thingWords = buildThingWords(picturableThings, generalThings);
const qualityWords = buildQualityWords(generalQualities, oppositeQualities);

console.log(`Generated ${thingWords.length} thing words.`);
console.log(`Generated ${qualityWords.length} quality words.`);

// 3. Merge
const allWords = [...operationWords, ...thingWords, ...qualityWords];
console.log(`Total words: ${allWords.length}`);

// 4. Verify counts
const opCount = allWords.filter(w => w.type === 'operation').length;
const thCount = allWords.filter(w => w.type === 'thing').length;
const qaCount = allWords.filter(w => w.type === 'quality').length;
console.log(`  Operations: ${opCount}`);
console.log(`  Things: ${thCount}`);
console.log(`  Qualities: ${qaCount}`);

if (allWords.length !== 850) {
  console.error(`ERROR: Expected 850 words but got ${allWords.length}`);
  process.exit(1);
}
if (opCount !== 100) {
  console.error(`ERROR: Expected 100 operation words but got ${opCount}`);
  process.exit(1);
}
if (thCount !== 600) {
  console.error(`ERROR: Expected 600 thing words but got ${thCount}`);
  process.exit(1);
}
if (qaCount !== 150) {
  console.error(`ERROR: Expected 150 quality words but got ${qaCount}`);
  process.exit(1);
}

// 5. Write output
const output = `window.BASIC_WORDS = ${JSON.stringify(allWords, null, 2)};
`;

fs.writeFileSync(targetPath, output, 'utf-8');
console.log(`\nSuccessfully wrote ${allWords.length} words to ${targetPath}`);
